/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.tables.records;


import com.example.demo.db.tables.Mobile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 全国手机号码段归属地
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MobileRecord extends UpdatableRecordImpl<MobileRecord> implements Record7<UInteger, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1548524571;

    /**
     * Setter for <code>test.mobile.id</code>. 主键
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.mobile.id</code>. 主键
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>test.mobile.phone</code>. 手机号码段
     */
    public void setPhone(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.mobile.phone</code>. 手机号码段
     */
    public String getPhone() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.mobile.province</code>. 省份
     */
    public void setProvince(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.mobile.province</code>. 省份
     */
    public String getProvince() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.mobile.city</code>. 市
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.mobile.city</code>. 市
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.mobile.service_provider</code>. 运营商
     */
    public void setServiceProvider(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.mobile.service_provider</code>. 运营商
     */
    public String getServiceProvider() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.mobile.city_code</code>. 区号
     */
    public void setCityCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.mobile.city_code</code>. 区号
     */
    public String getCityCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test.mobile.postcode</code>. 邮编
     */
    public void setPostcode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>test.mobile.postcode</code>. 邮编
     */
    public String getPostcode() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Mobile.MOBILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Mobile.MOBILE.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Mobile.MOBILE.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Mobile.MOBILE.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Mobile.MOBILE.SERVICE_PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Mobile.MOBILE.CITY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Mobile.MOBILE.POSTCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getServiceProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCityCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getServiceProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCityCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord value2(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord value3(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord value4(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord value5(String value) {
        setServiceProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord value6(String value) {
        setCityCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord value7(String value) {
        setPostcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MobileRecord
     */
    public MobileRecord() {
        super(Mobile.MOBILE);
    }

    /**
     * Create a detached, initialised MobileRecord
     */
    public MobileRecord(UInteger id, String phone, String province, String city, String serviceProvider, String cityCode, String postcode) {
        super(Mobile.MOBILE);

        set(0, id);
        set(1, phone);
        set(2, province);
        set(3, city);
        set(4, serviceProvider);
        set(5, cityCode);
        set(6, postcode);
    }
}
