/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db;


import com.example.demo.db.tables.Mobile;
import com.example.demo.db.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MOBILE_PHONE = Indexes0.MOBILE_PHONE;
    public static final Index MOBILE_PRIMARY = Indexes0.MOBILE_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MOBILE_PHONE = Internal.createIndex("phone", Mobile.MOBILE, new OrderField[] { Mobile.MOBILE.PHONE }, true);
        public static Index MOBILE_PRIMARY = Internal.createIndex("PRIMARY", Mobile.MOBILE, new OrderField[] { Mobile.MOBILE.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
