/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db;


import com.example.demo.db.tables.Mobile;
import com.example.demo.db.tables.User;
import com.example.demo.db.tables.records.MobileRecord;
import com.example.demo.db.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MobileRecord, UInteger> IDENTITY_MOBILE = Identities0.IDENTITY_MOBILE;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MobileRecord> KEY_MOBILE_PRIMARY = UniqueKeys0.KEY_MOBILE_PRIMARY;
    public static final UniqueKey<MobileRecord> KEY_MOBILE_PHONE = UniqueKeys0.KEY_MOBILE_PHONE;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MobileRecord, UInteger> IDENTITY_MOBILE = Internal.createIdentity(Mobile.MOBILE, Mobile.MOBILE.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<MobileRecord> KEY_MOBILE_PRIMARY = Internal.createUniqueKey(Mobile.MOBILE, "KEY_mobile_PRIMARY", Mobile.MOBILE.ID);
        public static final UniqueKey<MobileRecord> KEY_MOBILE_PHONE = Internal.createUniqueKey(Mobile.MOBILE, "KEY_mobile_phone", Mobile.MOBILE.PHONE);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }
}
