/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db;


import com.example.demo.db.tables.Mobile;
import com.example.demo.db.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 全国手机号码段归属地
     */
    public static final Mobile MOBILE = com.example.demo.db.tables.Mobile.MOBILE;

    /**
     * The table <code>test.user</code>.
     */
    public static final User USER = com.example.demo.db.tables.User.USER;
}
